"""empty message

Revision ID: 6829a8a2f166
Revises: c5e05954288b
Create Date: 2023-03-12 20:43:10.021570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6829a8a2f166'
down_revision = 'c5e05954288b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.Numeric(precision=17), nullable=True))
        batch_op.add_column(sa.Column('pages', sa.Numeric(precision=5, scale=0), nullable=True))
        batch_op.alter_column('words',
               existing_type=sa.NUMERIC(precision=5, scale=0),
               type_=sa.Numeric(precision=7, scale=0),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('words',
               existing_type=sa.Numeric(precision=7, scale=0),
               type_=sa.NUMERIC(precision=5, scale=0),
               existing_nullable=True)
        batch_op.drop_column('pages')
        batch_op.drop_column('isbn')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
